### ISSUE TITLE
issue with `qiskit.opflow` imports in `src/bias.py` due to updated Qiskit API

### ISSUE THREAD

**Issue by husisy** [Haozh20/Hamiltonian-Shadow-Repo#1]
Thank you for your great work! I recently started exploring your research and attempted to run your open-source code. However, I encountered the following error when executing `src/bias.py`:

```Python
In [1]: from qiskit.opflow import I,X,Y,Z
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from qiskit.opflow import I,X,Y,Z

ModuleNotFoundError: No module named 'qiskit.opflow'
```

I believe this issue is due to updates in the Qiskit API, as detailed in the [Qiskit migration guide](https://docs.quantum.ibm.com/api/migration-guides/qiskit-opflow-module).

To resolve this, I updated the imports to use the `qiskit.quantum_info.Pauli` class:

```Python
I = qiskit.quantum_info.Pauli('I')
X = qiskit.quantum_info.Pauli('X')
Y = qiskit.quantum_info.Pauli('Y')
Z = qiskit.quantum_info.Pauli('Z')
```

These changes allowed the script to run without errors (I am still running `src/bias.py` to verify). 

I have made this modification in my fork. Would you prefer I submit a pull request, or do you have a different solution in mind? 

Thank you for your time.

**Comment by Haozh20** [comment]
Thank you for following up on our work, and pointing out the incompatibility issue between our code and the Qiskit update! I believe your modification is correct, you could submit the pull request if you like. Thanks a lot!

p.s. I believe this import command also appears in other programs, so more modifications are needed when executing other programs.
